---
title: "explore ECHO data"
author: "Alex Huddell"
date: "9/7/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries and data

```{r }
library(tidyverse)
library(lubridate)
library(sf)
library(nhdplusTools)
library(here)
library(mapview)
library(leaflet)

dat<-read_csv(file=here('data','ECHO_data_clean.csv'))


```

Exploring the structure of the data through time, across permits, and across space.

```{r}
#looking at number of observations through time

dat %>%
  group_by(date) %>%
  tally() %>%
  ggplot(aes(date,n))+
  geom_col() +
  ylab("count of observations")+
  theme_minimal()


dat %>%
  group_by(permit_outfall) %>%
  tally() %>%
  ggplot(aes(x=n, y=permit_outfall))+
  geom_col()+
  xlab("count of observations")+
  ylab("permit and outfall numbers")

min(dat$date)
max(dat$date)


```

Sum monthly N loads by watershed through time.
```{r}
N_load_month_huc8<-dat %>%
  group_by(huc8, date)%>%
  summarize(sum(kg_N_TN_per_month, na.rm = T))


```

Make choropleth leaflet map to visualize N load by HUC8 data.
```{r}

#remove NAs from lat/ long
dat_noNA<- dat %>% drop_na(c('LONGITUDE_MEASURE','LATITUDE_MEASURE'))

#convert to sf obj
dat_sf <- st_as_sf(dat_noNA, coords = c('LONGITUDE_MEASURE', 'LATITUDE_MEASURE'), 
                   crs = 4326)
dat_sf


#extract huc8 codes 
HUC8<-nhdplusTools::get_huc8(AOI=dat_sf$geometry)

#viewing data extents on map
mapview(HUC8)
mapview(dat_sf)

leaflet() %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  setView(lng = -72.864817, lat = 42.119339,  zoom = 7)

```
