---
title: "format ECHO data"
author: "Alex Huddell"
date: "7/28/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries and data

```{r }
library(tidyverse)
library(lubridate)
library(here)

dat<-read_csv(file=here("data","PCS_LIS_watershed_data.csv"))

          
```


#Create key for each outfall/date and check how many rows per key.

```{r pressure, echo=FALSE}
dat$date<-ymd(dat$`Monitoring Dt (MVDT)`)

dat <- dat %>%
  mutate(days_per_month = days_in_month(date)) %>%
  mutate(key = paste0(`Permit Num (NPID)`,`Discharge Num (DSCH)`,date))

nrow(dat) #there are 196,586 rows
dat %>% count(key) #there are 95,366 unique keys, so some keys have duplicate rows

#looking at one of they keys:
test<-dat %>% filter(key=="CT000008611989-01-31")

#plot the frequency of different parameters
dat$params<-as.factor(dat$"Parameter Cd (PRAM)")
levels(dat$params)

levels<-dat %>%
  group_by(params) %>%
  tally()

ggplot(levels, aes(params,n))+
  geom_col() +
  ylab("count of observations")+
  theme(axis.text.x=element_text(angle = 30, hjust=1))



```